server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: travel-itinerary-planner

  datasource:
    url: jdbc:postgresql://localhost:5432/travel_planner
    username: ${DB_USERNAME:travel_user}
    password: ${DB_PASSWORD:travel_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: admin

logging:
  level:
    com.travelplanner: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
